# gateway/src/main/resources/application.yaml
spring:
  application:
    name: gateway

  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/auth/**,/swagger-ui/**,/v3/api-docs/**,/actuator/health

        - id: user-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/users/**
          filters:
            - name: JwtAuthentication

        - id: ticket-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/tickets/**
          filters:
            - name: JwtAuthentication

  main:
    web-application-type: reactive

server:
  port: 8080

logging:
  level:
    com.example.gateway: DEBUG
    org.springframework.cloud.gateway: DEBUG