server:
  port: 8084

spring:
  application:
    name: document-service

  cloud:
    compatibility-verifier:
      enabled: false

  datasource:
    url: jdbc:postgresql://80.93.62.239:5432/prism
    username: postgres
    password: 12Hiro0016
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

# MinIO Configuration
minio:
  endpoint: http://localhost:9000
  access-key: minioadmin
  secret-key: minioadmin
  bucket-name: ticket-files

# JWT Configuration
jwt:
  public-key: classpath:public-key.pem

# Logging
logging:
  level:
    com.example.document_service: DEBUG
    org.springframework.security: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info