server:
  port: 8083

spring:
  application:
    name: workflow-service
  
  datasource:
    url: jdbc:postgresql://localhost:5433/prism
    username: marcello
    password: 13578900
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false # ✅ Отключаем warning

  kafka:
    bootstrap-servers: localhost:9092
    
    consumer:
      group-id: workflow-service-group
      auto-offset-reset: earliest
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.json.trusted.packages: com.example.workflowservice.model.event
        spring.json.type.mapping: \
          event:com.example.workflowservice.model.event.BaseEvent,\
          workflow_status:com.example.workflowservice.model.event.WorkflowStatusEvent
    
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      retries: 3

springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha

logging:
  level:
    com.example.workflowservice: DEBUG
    org.springframework.kafka: INFO